module.exports = {

  FRAMEWORK_MESSAGE_CONTAINER_UPDATED_PROPS: 'frameworkMessageContainerUpdatedProps',

  WEBCODESK_MESSAGE_START_LISTENING_TO_FRAMEWORK: 'webcodeskMessageStartListeningToFramework',
  WEBCODESK_MESSAGE_STOP_LISTENING_TO_FRAMEWORK: 'webcodeskMessageStopListeningToFramework',

  WEBCODESK_MESSAGE_COMPONENT_RESOURCE_INDEX: 'WEBCODESK_MESSAGE_COMPONENT_RESOURCE_INDEX',
  WEBCODESK_MESSAGE_COMPONENT_STORY_RESOURCE_INDEX: 'WEBCODESK_MESSAGE_COMPONENT_STORY_RESOURCE_INDEX',

  WEBCODESK_MESSAGE_PAGE_COMPONENTS_TREE: 'WEBCODESK_MESSAGE_PAGE_COMPONENTS_TREE',

};
